name: SimplifiedSearch-release

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  BuildConfiguration: Release

jobs:
  release:
    permissions:
      packages: write
      contents: read
    runs-on: 'ubuntu-latest'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c ${{ env.BuildConfiguration }} --no-restore
    - name: Test
      run: dotnet test -c ${{ env.BuildConfiguration }} --no-build
    - name: Pack
      run: dotnet pack -c ${{ env.BuildConfiguration }} --no-build
      
